type PrivilegedAccessEntry = {
  readonly file: string;
  readonly purpose: string;
  readonly riskLevel: "HIGH" | "MEDIUM";
  readonly mitigations: readonly string[];
  /** Strict legitimacy criterion met: L1=cross-tenant RLS block, L2=system bootstrap, L3=security primitive, L4=cross-tenant aggregation. Absent means strict criteria not met. */
  readonly strictCriteriaMet?: "L1" | "L2" | "L3" | "L4";
  /** True when strict criteria are not met but a swap requires a new or corrected RLS policy first. */
  readonly needsRlsBeforeSwap: boolean;
};

export const PRIVILEGED_ACCESS_REGISTRY: readonly PrivilegedAccessEntry[] = [
  {
    file: "src/lib/security/agent-attestation.ts",
    purpose: "Nonce-based replay protection for agent tokens: nonces are written on first use and checked before processing to prevent token reuse. Must bypass user RLS because a compromised token could be used to defeat its own revocation check.",
    riskLevel: "HIGH",
    mitigations: [
      "Nonce hashed with SHA-256 before storage",
      "Expires at token expiry time",
      "Race condition handled via unique-constraint (error code 23505)",
      "Replay attempts logged to security telemetry",
    ],
    strictCriteriaMet: "L3",
    needsRlsBeforeSwap: false,
  },
  {
    file: "src/lib/security/telemetry.ts",
    purpose: "Security audit trail persistence: all security events (auth denials, scope violations, privileged access) are written to the security_events table. Must use service role because security events must be recorded even when the user session is invalid, and RLS on security_events must not be bypassable by the actor being logged.",
    riskLevel: "HIGH",
    mitigations: [
      "allowTelemetryRecursionBypass prevents infinite logging loops",
      "Metadata scrubbed of secrets (token, password, cookie, etc.) before persistence",
      "console.warn emitted as secondary channel",
    ],
    strictCriteriaMet: "L3",
    needsRlsBeforeSwap: false,
  },
  {
    file: "src/lib/governance/authority/runtime/governance-core.ts",
    purpose: "Approval request persistence: governance decisions requiring human approval are persisted to governance_approval_requests. INSERT is revoked for the authenticated role in the RLS migration; the record is created by the system on behalf of the requesting actor, not by the actor directly.",
    riskLevel: "HIGH",
    mitigations: [
      "Only writes approval records after governance evaluation completes",
      "Workspace scope always enforced before write",
      "Logged to security telemetry via finalize()",
    ],
    strictCriteriaMet: "L1",
    needsRlsBeforeSwap: false,
  },
  {
    file: "src/lib/security/trust-domains.ts",
    purpose: "Trust domain and signing key lifecycle management: reads/writes trust domains, signing keys, and verifier policies for the capability claims infrastructure. These tables span tenant boundaries and cannot be governed by single-tenant RLS.",
    riskLevel: "HIGH",
    mitigations: [
      "Only called from capability claim issuance and verification paths",
      "Key revocation immediately reflected in subsequent verifications",
      "All mutations logged to security telemetry",
    ],
    strictCriteriaMet: "L3",
    needsRlsBeforeSwap: false,
  },
  {
    file: "src/lib/security/trust-handshakes.ts",
    purpose: "External verifier handshake protocol: manages the handshake lifecycle between this issuer and external verifiers. Cross-tenant by design — a verifier from one domain establishing trust with another domain cannot be scoped to either tenant's RLS context.",
    riskLevel: "HIGH",
    mitigations: [
      "Handshake token stored as SHA-256 hash only",
      "Expiry enforced at validation time",
      "Approvals require explicit admin action",
      "All state changes logged to security telemetry",
    ],
    strictCriteriaMet: "L3",
    needsRlsBeforeSwap: false,
  },
  {
    file: "src/lib/security/trust-coordination.ts",
    purpose: "Trust graph, revocation registry, and trust anchor management: cross-tenant revocation checks and trust graph operations must be authoritative regardless of which tenant context initiates the query.",
    riskLevel: "HIGH",
    mitigations: [
      "Revocations immediately propagated to revocation registry",
      "Trust graph edges scoped by source/target domain",
      "Quarantine path for unsafe imports",
      "All mutations logged to security telemetry",
    ],
    strictCriteriaMet: "L3",
    needsRlsBeforeSwap: false,
  },
  {
    file: "src/lib/governance/authority/runtime/execution-grants.ts",
    purpose: "Governance execution grant lifecycle: issues, validates, and consumes single-use execution grants after governance approval. INSERT/UPDATE/DELETE on governance_execution_grants are revoked for the authenticated role in the RLS migration; grants span approval request, actor, and resource tables that cross user-level RLS boundaries.",
    riskLevel: "HIGH",
    mitigations: [
      "Grant issued only after explicit governance approval",
      "Single-use enforced via atomic status transition to 'consumed'",
      "Token stored as SHA-256 hash only",
      "Replay attempts logged to security telemetry",
      "All operations scoped to workspaceId",
    ],
    strictCriteriaMet: "L1",
    needsRlsBeforeSwap: false,
  },
  {
    file: "src/lib/governance/authority/runtime/delegated-capabilities.ts",
    purpose: "Delegated capability chain: issues, validates, revokes, and consumes delegated capabilities that may flow across user and agent actors within a workspace. The delegation chain resolver must traverse records owned by multiple actors.",
    riskLevel: "HIGH",
    mitigations: [
      "Delegation depth enforced (max 3 hops)",
      "Scope-broadening attempts blocked at assertion layer",
      "Self-delegation loops detected and rejected",
      "Token stored as SHA-256 hash only",
      "All operations scoped to workspaceId",
    ],
    strictCriteriaMet: "L1",
    needsRlsBeforeSwap: false,
  },
  {
    file: "src/app/api/governance/trust/handshakes/route.ts",
    purpose: "Admin listing of all verifier handshakes across all trust domains. Cross-tenant by design — the admin view must show all handshakes regardless of workspace ownership.",
    riskLevel: "HIGH",
    mitigations: [
      "Serves admin/system review purposes only",
      "No sensitive key material exposed in response",
      "Results limited to 100 records",
    ],
    strictCriteriaMet: "L1",
    needsRlsBeforeSwap: false,
  },
  {
    file: "src/app/api/governance/trust/events/route.ts",
    purpose: "Cross-verifier trust event listing: serves trust event data for trusted synchronization between verifiers. Events span trust domains and cannot be scoped to a single tenant's RLS context.",
    riskLevel: "HIGH",
    mitigations: [
      "Filterable by trust domain, event type, severity, and time window",
      "Results capped at 500 records",
      "Event data does not include secret key material",
    ],
    strictCriteriaMet: "L1",
    needsRlsBeforeSwap: false,
  },
  {
    file: "src/app/api/governance/trust/events/import/route.ts",
    purpose: "Trust event ingestion from external verifiers: after handshake validation, persists incoming trust events to the local event store and triggers revocation registration. Cross-tenant operation with external origin.",
    riskLevel: "HIGH",
    mitigations: [
      "Handshake token validated before any write",
      "Event cryptographic signature verified before acceptance",
      "Rejected events logged to security telemetry",
      "Accepted events trigger revocation registry update",
    ],
    strictCriteriaMet: "L1",
    needsRlsBeforeSwap: false,
  },
  {
    file: "src/lib/billing.ts",
    purpose: "Stripe webhook idempotency lifecycle (begin/processed/ignored/failed) and company_subscriptions reads/writes: Stripe webhooks arrive without a user session, and the idempotency guard must write to billing_webhook_events atomically to prevent duplicate or lost-failure processing. getCompanySubscription/updateCompanySubscription/findCompanyIdByStripeCustomerId/findCompanyIdByStripeSubscriptionId accept an optional caller-supplied client so the webhook route's single post-verification privileged client can be reused across the whole request instead of re-instantiating per call. company_subscriptions has no authenticated write policy (Perilla 7 — 20260818000000_supabase_rls_service_role_boundary_hardening.sql): the only two approved writers are this file (billing webhook lifecycle) and src/app/api/billing/create-checkout-session/route.ts, which calls updateCompanySubscription with useServiceRole:true to persist a first-time Stripe customer id after its own requireBillingManageMembership check — that route does not call createSupabaseServiceRoleClient/createPrivilegedSupabaseClient directly, it only sets useServiceRole on this file's exported functions, so it is documented here rather than as a separate registry entry.",
    riskLevel: "HIGH",
    mitigations: [
      "Webhook signature verified in the route before any of these functions are called with useServiceRole — see src/app/api/billing/webhook/route.ts",
      "systemActor set to 'stripe_webhook' for audit trail on the idempotency table",
      "Idempotency enforced via unique constraint on event_id (error code 23505); a claimed-but-crashed event is marked 'failed' (not 'processed') so Stripe's automatic redelivery can retry it exactly once at a time via an atomic conditional UPDATE",
      "error_reason values are sanitized (newlines stripped, capped at 500 chars) before being persisted — never raw error objects, stack traces, or secrets",
      "See docs/security/stripe-webhook-billing-lifecycle-boundary.md (Perilla 6)",
    ],
    strictCriteriaMet: "L2",
    needsRlsBeforeSwap: false,
  },
  {
    file: "src/app/api/billing/webhook/route.ts",
    purpose: "Stripe webhook route: the sole entrypoint where an unauthenticated, internet-facing request is allowed to mutate company_subscriptions. Instantiates the privileged Supabase client used for the rest of the request (idempotency claim, mapping lookups, lifecycle mutation) exactly once, and only after stripe.webhooks.constructEvent has verified the request's signature against the raw body.",
    riskLevel: "HIGH",
    mitigations: [
      "Raw body (request.text()) read and passed to verifyStripeWebhookEvent before any JSON parsing or metadata access; request.json()/JSON.parse never called on the body",
      "Fails closed (400) on missing signature, missing STRIPE_WEBHOOK_SECRET, or constructEvent throwing — createPrivilegedSupabaseClient is never called on any of these paths",
      "Billing mutation only reachable via resolveStripeBillingLifecycleDecision (src/lib/billing-webhook-lifecycle.ts), which validates customer/subscription against the server-side company_subscriptions mapping and the price id against the server-side plan catalog before returning anything other than action: 'ignore' — Stripe metadata (companyId/userId/plan) is read only as a mismatch-logging hint, never as authorization",
      "A processing exception marks the event 'failed' (retryable) instead of silently swallowing it or leaving it stuck as 'processed'",
      "Error responses return a generic message only — no error.message, stack trace, or event payload is ever included in the HTTP response",
      "See docs/security/stripe-webhook-billing-lifecycle-boundary.md (Perilla 6)",
    ],
    strictCriteriaMet: "L2",
    needsRlsBeforeSwap: false,
  },
  {
    file: "src/lib/workspaces.ts",
    purpose: "Workspace bootstrap on first login: creates the user's default workspace and membership record. The user has no existing workspace at this point so RLS policies (which restrict access to workspace members) would block the write.",
    riskLevel: "HIGH",
    mitigations: [
      "actorUserId always set to the authenticated user performing bootstrap",
      "upsert with ignoreDuplicates prevents race-condition double-creation",
      "Only creates workspace if no existing membership found",
    ],
    strictCriteriaMet: "L2",
    needsRlsBeforeSwap: false,
  },
  {
    file: "src/lib/feature-gates.ts",
    purpose: "Feature gate enforcement: getCompanyIdByUserId uses supabase.auth.admin.getUserById() which is only available via the service role client — there is no scoped-client equivalent for reading another user's auth metadata. canCreateMoreProjects counts all user projects for limit enforcement.",
    riskLevel: "HIGH",
    mitigations: [
      "auth.admin API requires service role — no scoped alternative exists",
      "Company ID resolved from user metadata, not user-controllable input",
      "Project count enforced server-side, never trusted from client",
    ],
    strictCriteriaMet: "L1",
    needsRlsBeforeSwap: false,
  },
  {
    file: "src/lib/db/supabase-server.ts",
    purpose: "Legacy service-role client factory (createSupabaseAdminClient): creates a service role client without the mandatory PrivilegedAccessContext tracking. No active external callers confirmed — this factory should be deleted once confirmed unused. Strict criteria L1–L4 do not apply because no queries are executed by this file directly.",
    riskLevel: "HIGH",
    mitigations: [
      "console.warn emitted on every instantiation",
      "No active callers confirmed — defined but not externally imported",
      "New code must use createPrivilegedSupabaseClient from src/lib/security/privileged-access.ts",
    ],
    needsRlsBeforeSwap: false,
  },
  {
    file: "src/app/(protected)/layout.tsx",
    purpose: "Trial status enforcement: reads workspace memberships and trial license status, then expires and records events for inactive trials. The trial expiry mutation and event insertion are system-level writes across workspace boundaries that RLS on the authenticated user would block.",
    riskLevel: "MEDIUM",
    mitigations: [
      "Authenticated user required (requireAuthUser)",
      "Only executed for non-founder/non-internal users",
      "Trial expiry is idempotent (updates only active trials past end date)",
    ],
    strictCriteriaMet: "L1",
    needsRlsBeforeSwap: false,
  },
  {
    file: "src/lib/workspace-team.ts",
    purpose: "Workspace invitation acceptance (acceptWorkspaceInvite, called from src/app/(protected)/accept-invite/[token]/page.tsx), member role updates (updateWorkspaceMemberRole), and assignee display-name resolution (listWorkspaceMembersForAssignment, used by the Quick Add Task assignee selector): invite acceptance looks up an invitation by opaque token and creates a workspace membership for a user not yet a member of the target workspace; role update reads the actor's and target's own workspace_memberships rows and writes an updated role; listWorkspaceMembersForAssignment reads real workspace_memberships rows and resolves each member's email/display name via auth.admin.getUserById, since there is no profiles table and reading another user's auth metadata has no scoped-client equivalent. workspace_memberships has only SELECT RLS policies (see 20260515100000_rls_governance_fixes.sql) — there is no policy permitting a client-side UPDATE at all, so the role-update write must go through the service role regardless of the actor's role, and using one privileged client for the whole role-update flow avoids an RLS-scoped read resolving 'target not found' for a real member just because the actor lacks read visibility into other members' rows. MEMBERSHIP OFFBOARDING (removeWorkspaceMember, called from DELETE /api/workspace-team/members, added by P0-LAUNCH-05): deletes a workspace_memberships row to remove tenant authority while deliberately leaving the auth.users identity intact. workspace_memberships has only SELECT RLS policies, so there is no policy permitting a client-side DELETE at all and the removal must go through the service role regardless of the actor's role — the same reason the role-update write does.",
    riskLevel: "MEDIUM",
    mitigations: [
      "Authenticated user required",
      "Invite email must match the authenticated user's email (assertInviteBelongsToAuthenticatedEmail) — closes a prior gap where any authenticated user could accept any token regardless of who it was addressed to",
      "Token validated for pending status, non-revocation, and non-expiry before any write",
      "Assigned role always read from the invite record (never from a caller parameter) and re-validated with normalizeWorkspaceRole",
      "Pending→accepted transition is a single conditional UPDATE checked before any membership write, so a concurrent replay of the same token can win at most once",
      "Membership write uses upsert to prevent duplicates",
      "Audit event written to workspace_audit_events on completion",
      "updateWorkspaceMemberRole resolves actorRole/currentTargetRole from workspace_memberships server-side (never from a body/metadata/display-role field) and only writes after canUpdateWorkspaceMemberRole returns \"allow\" — owner assignment, last-owner changes, and self-promotion are denied before any UPDATE runs",
      "listWorkspaceMembersForAssignment requires requireWorkspaceMember(workspaceId) before any read, only returns members already present in workspace_memberships for that workspace (never fabricated or cross-workspace), and never returns auth secrets — only id/display name/email/role",
      "removeWorkspaceMember requires an authenticated session at the HTTP boundary (DELETE /api/workspace-team/members); an unauthenticated caller receives 401 and never reaches the domain",
      "removeWorkspaceMember resolves BOTH the actor's and the target's workspace_memberships rows server-side — never from a request body, metadata, or display-role field",
      "Removal applies the canonical owner/admin hierarchy (evaluateWorkspaceMembershipRemoval), which is deliberately no weaker than canUpdateWorkspaceMemberRole: pm/viewer may remove nobody, admin may remove pm/viewer only and never another admin, and self-removal is denied",
      "An OWNER target can never be removed through this boundary — deny_last_owner for the final owner, deny_owner_removal_requires_transfer otherwise — so no concurrent pair of owner removals can orphan a workspace",
      "A cross-tenant actor with no membership in the requested workspace fails closed (deny_actor_insufficient_role); the workspace is never inferred from the caller",
      "A successful removal attempts a checked member_removed audit write; the insert result is inspected and a failure is surfaced as offboarding_audit_write_failed rather than reported as clean success",
      "Membership deletion and the audit write are separate persistent operations, so an audit failure can follow authority removal — covered by RR-OFFBOARD-AUDIT-NONATOMIC; operators must inspect effective membership first and reconcile rather than blindly retry",
      "See docs/security/invite-workspace-role-boundary.md and docs/security/workspace-role-update-boundary.md",
    ],
    strictCriteriaMet: "L2",
    needsRlsBeforeSwap: false,
  },
  {
    file: "src/app/(protected)/early-access/page.tsx",
    purpose: "Founder early access dashboard: reads all early_access_invites, trial_licenses, workspace_activations, and telemetry for the founder operations view. Data spans all workspaces and cannot be scoped to a single user.",
    riskLevel: "MEDIUM",
    mitigations: [
      "Authenticated user required (requireAuthUser)",
      "isFounderOrInternalUser gate required before the service-role client is instantiated or any query runs — a non-founder authenticated user gets notFound() (404), not partial/empty data (Perilla 5: previously this page had no founder gate at all — any signed-in user could view all invite emails, trial status, and telemetry)",
      "Reads are display-only — no mutations from this page",
      "Results limited per table (limit 20–400)",
      "actorUserId threaded into the privileged access context for telemetry attribution",
    ],
    strictCriteriaMet: "L1",
    needsRlsBeforeSwap: false,
  },
  {
    file: "src/app/api/early-access/summary/route.ts",
    purpose: "Founder early access summary API: runs a trial expiry sweep and returns aggregate status across all invites, trials, activations, and events. Aggregation spans all workspaces and cannot be scoped to a single tenant.",
    riskLevel: "MEDIUM",
    mitigations: [
      "isFounderOrInternalUser check required before any operation, including before the service-role client is instantiated",
      "Authenticated user required",
      "Trial expiry sweep uses a scoped, parameterized `.update().eq().lt()` call (Perilla 5: previously called a generic `execute_sql` RPC with an inline query string — a raw-SQL-shaped pattern removed in favor of the query builder; the RPC also does not exist in any migration, so the sweep was silently a no-op)",
      "Sweep is idempotent (expires only active trials past end date)",
      "actorUserId threaded into the privileged access context for telemetry attribution",
    ],
    strictCriteriaMet: "L4",
    needsRlsBeforeSwap: false,
  },
  {
    file: "src/lib/early-access.ts",
    purpose: "Early access invite and trial lifecycle management: creates invites, sends emails, records trial events, approves/revokes access. These are system-managed records not owned by any single user and span tenant boundaries.",
    riskLevel: "MEDIUM",
    mitigations: [
      "All mutations logged to early_access_events for audit trail, including a sanitized (trimmed, 500-char-capped) actor-supplied reason for revoke/extend actions",
      "Invite tokens generated with 24 random bytes (192 bits of entropy), stored hashed (SHA-256)",
      "Trial status transitions are explicit and logged",
      "acceptEarlyAccessInvite requires the authenticated user's email to match invite_email — closes a prior gap where any authenticated user with the token could activate another person's invite (see docs/security/invite-workspace-role-boundary.md)",
      "requireNonEmptyId validates every founder-action target id (inviteId/trialId) before any query is built — an empty/missing id fails closed rather than reaching a service-role filter",
      "isValidTrialExtensionDays rejects NaN/Infinity/non-integer/out-of-range durations (Perilla 5: previously `extensionDays <= 0 || extensionDays > 60` silently passed NaN through)",
      "isValidInviteEmail validates invite email shape before the service-role client is instantiated",
      "actorUserId threaded into every privileged access context for telemetry attribution",
      "See docs/security/admin-founder-endpoint-boundary.md (Perilla 5)",
    ],
    strictCriteriaMet: "L1",
    needsRlsBeforeSwap: false,
  },
  {
    file: "src/lib/founder-program/db.ts",
    purpose:
      "Founder Circle Program service surface (single factory for the whole src/lib/founder-program domain): all founder_* tables are deliberately service-role-only — operator views aggregate program data across all workspaces, and participant writes (application, feedback, withdrawal) are validated in route handlers against tables that grant clients no insert/update/delete at all. Participant reads use narrow column-scoped self-select RLS policies, never this client.",
    riskLevel: "MEDIUM",
    mitigations: [
      "Single factory (createFounderProgramDbClient) — no other founder-program file may construct a privileged client, keeping the audit surface to one entry",
      "Every operator route checks isFounderOrInternalUser before parsing the body or instantiating the client; denials logged as founder_program_denied",
      "Every participant route resolves the participant record by the authenticated user id before any mutation (self-scoping in the route layer on top of RLS)",
      "All lifecycle state changes go through the founder_program_transition SECURITY DEFINER function (settings row locked, capacity checked, compare-and-swap state update, append-only audit row) — execute granted only to service_role",
      "Invitation tokens generated with 24 random bytes (192 bits), stored as SHA-256 only; token_hash is never selectable by client roles and never logged",
      "Feature flags fail closed: with PMFREAK_FOUNDER_PROGRAM_* unset, routes return controlled responses before this client is ever created",
      "actorUserId threaded into the privileged access context for telemetry attribution",
      "See docs/founder-program/05-authorization-model.md",
    ],
    strictCriteriaMet: "L4",
    needsRlsBeforeSwap: false,
  },
  {
    file: "src/lib/auth/resolve-onboarding-state.ts",
    purpose: "Onboarding/trial-gate resolver: reads the caller's workspace memberships and active trial license, and expires it server-side if past trial_end_at, to decide routing (no_workspace/needs_project/active/trial_blocked — no PMO precondition). System-level write across workspace boundaries that RLS on the authenticated user would block.",
    riskLevel: "MEDIUM",
    mitigations: [
      "Authenticated AuthUserContext required by signature",
      "isFounderOrInternalUser(user) skips the trial-gate branch entirely for founders/internal — never widened to trust user_metadata.role or display role",
      "Trial expiry write uses a scoped, parameterized `.update().eq().eq().lt()` call (Perilla 5: previously called a generic `execute_sql` RPC with the trial id interpolated into an inline query string — a raw-SQL-shaped pattern removed in favor of the query builder; the RPC also does not exist in any migration, so the sweep was silently a no-op, meaning trials never actually transitioned to expired via this path)",
      "Expiry is idempotent (only updates a trial matched by id AND still active AND past trial_end_at)",
    ],
    strictCriteriaMet: "L1",
    needsRlsBeforeSwap: false,
  },
  {
    file: "src/lib/first-user-telemetry.ts",
    purpose: "First-user onboarding telemetry: persists anonymous onboarding events to first_user_telemetry_events. May be called before or without an authenticated user session during the onboarding flow.",
    riskLevel: "MEDIUM",
    mitigations: [
      "systemActor set to 'system' for audit trail",
      "No user-controlled data in operation payload beyond eventType enum",
      "Insert-only operation",
    ],
    strictCriteriaMet: "L2",
    needsRlsBeforeSwap: false,
  },
  {
    file: "src/app/api/governance/trust/keys/route.ts",
    purpose: "Public key discovery endpoint: serves public key metadata for external verifiers to discover asymmetric signing keys. HMAC secret key material is never exposed; only public JWK and PEM. Key metadata spans all trust domains.",
    riskLevel: "MEDIUM",
    mitigations: [
      "Only public key material returned (public_key_jwk, public_key_pem)",
      "HMAC secret key material explicitly excluded per response mapping",
      "Access logged to security telemetry",
    ],
    strictCriteriaMet: "L1",
    needsRlsBeforeSwap: false,
  },
  {
    file: "src/app/api/governance/trust/.well-known/capability-issuer/route.ts",
    purpose: "Capability issuer discovery (.well-known): public endpoint serving trust domain metadata for external verifiers. Analogous to OAuth .well-known/openid-configuration. Metadata spans all trust domains.",
    riskLevel: "MEDIUM",
    mitigations: [
      "No sensitive data returned — only metadata, supported algorithms, and active key IDs",
      "Access logged to security telemetry",
      "Trust domain list reflects current database state",
    ],
    strictCriteriaMet: "L1",
    needsRlsBeforeSwap: false,
  },
  // ── Perilla 7 additions (2026-07-10) — files calling createSupabaseServiceRoleClient
  // or createPrivilegedSupabaseClient directly that were not yet registered. ──
  {
    file: "src/lib/storage/upload-provider.ts",
    purpose: "Supabase Storage upload/delete/download for evidence documents. The 'pmfreak-documents' bucket's storage.objects policy (20260515200000_storage_bucket_setup.sql) grants access to service_role only — 'No authenticated direct access — all access goes through API routes' — so there is no scoped-client alternative for any storage operation on this bucket.",
    riskLevel: "HIGH",
    mitigations: [
      "storage.objects RLS on this bucket has no authenticated policy at all — service role is the only way to reach it, by design",
      "Storage path is namespaced by companyId/projectId/fileId, all resolved server-side from an already-authorized upload/evidence flow, never from raw client input",
      "File name sanitized before use in the storage path",
    ],
    strictCriteriaMet: "L1",
    needsRlsBeforeSwap: false,
  },
  {
    file: "src/lib/project-evidence/evidence-processor.ts",
    purpose: "Asynchronous evidence extraction: reads/updates project_evidence and upserts project_evidence_content after a document upload has already been authorized. Runs via setTimeout as a fire-and-forget background job (processEvidenceInBackground), after the HTTP response has already been sent — there is no request-scoped cookie/session left to build a scoped client from by the time this code runs, even though project_evidence/project_evidence_content both have workspace-member RLS policies that would otherwise permit a scoped read for an in-request caller.",
    riskLevel: "MEDIUM",
    mitigations: [
      "evidenceId is only ever passed in from a prior authorized upload route, never client-supplied at this layer",
      "Failure path marks the evidence row 'failed' rather than leaving it stuck in 'processing'",
      "Reuses getUploadProvider().download, itself service-role-gated for the same reason (no session left to scope)",
    ],
    strictCriteriaMet: "L2",
    needsRlsBeforeSwap: false,
  },
  {
    file: "src/lib/project-discovery/discovery-repository.ts",
    purpose: "regenerateProjectDiscovery reads project_evidence_content and reads/inserts project_discovery, then triggers RAID/recommended-action materialization. Invoked either synchronously from the evidence processor's background job or via regenerateProjectDiscoveryInBackground (another setTimeout deferral) — same no-session-left-to-scope justification as evidence-processor.ts. project_discovery/project_evidence_content both have workspace-member RLS policies; this is a background/system operation, not a user request.",
    riskLevel: "MEDIUM",
    mitigations: [
      "projectId is only ever sourced from an already-processed evidence row, never client input at this layer",
      "Payload hash comparison skips redundant version writes (idempotent by construction)",
      "Errors logged with requestId/projectId, re-thrown to the caller rather than swallowed",
    ],
    strictCriteriaMet: "L2",
    needsRlsBeforeSwap: false,
  },
  {
    file: "src/lib/pmo/save-team-invites.ts",
    purpose: "PMO onboarding wizard: inserts pmo_team_invites rows after resolving the authenticated user's own workspace via resolveCanonicalWorkspace. pmo_team_invites (20260528000000_pmo_team_invites.sql) has only a SELECT policy for workspace members — there is no authenticated INSERT policy at all, so a scoped client cannot perform this write regardless of the actor's role.",
    riskLevel: "MEDIUM",
    mitigations: [
      "getAuthUser() required before any query",
      "workspaceId always comes from resolveCanonicalWorkspace(user.id), never a client-supplied field",
      "Invite emails validated (non-empty, RFC-shaped) before insert",
    ],
    strictCriteriaMet: "L1",
    needsRlsBeforeSwap: false,
  },
  {
    file: "src/lib/pmo/save-pmo-tenant.ts",
    purpose: "PMO onboarding completion ('use server' action): upserts workspace_governance and updates workspaces for the caller's own resolved workspace, then calls supabase.auth.admin.updateUserById to mark onboarding_completed — the auth.admin API is only available via service role, with no scoped-client equivalent, which is why the whole flow (including the workspace_governance/workspaces writes, both of which do have member-scoped RLS policies that would otherwise permit a scoped write) shares one privileged client: the rollback-on-failure path deletes the just-inserted workspace_governance row with the same client that wrote it, avoiding a second auth context resolution mid-transaction.",
    riskLevel: "MEDIUM",
    mitigations: [
      "getAuthUser() required before any query",
      "workspaceId always comes from resolveCanonicalWorkspace(user.id), never a client-supplied field",
      "Explicit rollback (delete) of the workspace_governance row if a later step in the same flow throws",
      "no longer writes any onboarding_completed flag — activation state is derived from the real pmos/projects rows this flow already writes",
    ],
    strictCriteriaMet: "L1",
    needsRlsBeforeSwap: false,
  },
  {
    file: "src/lib/pmo/save-workspace-governance.ts",
    purpose: "PMO governance wizard ('use server' action): upserts workspace_governance for the caller's own resolved workspace. workspace_governance has a member-scoped 'for all' RLS policy (20260527091000_workspace_governance.sql) that would permit a scoped write for this exact operation — service role is used here for consistency with save-pmo-tenant.ts's write to the same table, not because RLS blocks it. Documented as a SWAP candidate rather than swapped in this pass to avoid touching the shared onboarding-wizard write path without a live-DB regression pass.",
    riskLevel: "MEDIUM",
    mitigations: [
      "getAuthUser() required before any query",
      "workspaceId always comes from resolveCanonicalWorkspace(user.id), never a client-supplied field",
    ],
    needsRlsBeforeSwap: false,
  },
  {
    file: "src/lib/pmo/load-pmo-tenant.ts",
    purpose: "Reads workspace_governance for a caller-supplied workspaceId. Every call site (src/app/(protected)/pmo/invite-team/page.tsx, src/app/api/copilot/route.ts, src/app/api/pmo/context/route.ts, src/lib/auth/resolve-onboarding-state.ts) resolves workspaceId via resolveCanonicalWorkspace(user.id) first, so the id is always the authenticated caller's own workspace — workspace_governance's member-scoped RLS policy would permit a scoped read for this exact case. Documented as a SWAP candidate, not swapped in this pass (shared read path used by four call sites).",
    riskLevel: "MEDIUM",
    mitigations: [
      "workspaceId is always caller-resolved via resolveCanonicalWorkspace, never accepted directly from a request body/query param at this layer",
      "Read-only; failures degrade to { found: false } rather than throwing",
    ],
    needsRlsBeforeSwap: false,
  },
  {
    file: "src/lib/workspaces/canonical-workspace-resolver.ts",
    purpose: "resolveCanonicalWorkspace reads workspace_memberships and workspaces for a caller-supplied userId to pick the user's active workspace. Both tables have policies that already permit this exact read for an authenticated user reading their own rows (users_can_read_own_workspace_memberships, 20260515100000_rls_governance_fixes.sql) — service role is used for convenience/consistency since this function is called from many contexts (pages, server actions, background jobs) with varying session availability, not because RLS blocks the read for the common case. Documented as a SWAP candidate for the request-scoped call sites; the background-job call sites (e.g. inside 'use server' actions invoked from client forms) may still need it. Not swapped in this pass — this function is on the critical path for workspace resolution across the whole app and warrants a dedicated regression pass before narrowing.",
    riskLevel: "MEDIUM",
    mitigations: [
      "userId is always the resolved authenticated caller's own id, never a client-supplied 'view as' parameter",
      "Read-only",
      "Archived/deleted workspaces filtered out before a workspaceId is returned",
    ],
    needsRlsBeforeSwap: false,
  },
  {
    file: "src/lib/workspaces/routed-workspace.ts",
    purpose: "resolveRoutedWorkspace authorizes a workspace id that arrived from a ROUTE segment (or was bound into a Server Action) against the caller's own workspace_memberships row and that workspace's status. It is the sibling of canonical-workspace-resolver.ts and exists because that resolver FALLS BACK to a different workspace when its hint is unusable — correct for a stale cookie, unsafe for a URL, where falling back means acting on a tenant the caller never named. It reads the same two tables under the same policies (users_can_read_own_workspace_memberships) and uses the service role for the same reason: it is called from pages, Server Actions and a layout with varying session availability. Documented as a SWAP candidate alongside canonical-workspace-resolver.ts and should be narrowed in the same pass, not separately.",
    riskLevel: "MEDIUM",
    mitigations: [
      "userId is always the resolved authenticated caller's own id, never a client-supplied 'view as' parameter",
      "Read-only — it performs no insert, update or delete",
      "The client-supplied workspaceId is used ONLY as an equality filter on the caller's own membership row; a workspace the caller is not a member of returns denied, so the parameter can narrow the answer but never widen it",
      "Deleted workspaces and absent memberships collapse to one indistinguishable 'denied' result, so the id cannot be used to probe which workspaces exist",
      "Fails closed: a failed membership or workspace read returns denied rather than proceeding",
    ],
    needsRlsBeforeSwap: false,
  },
  {
    file: "src/lib/projects/first-insight/operational-governance-brief-store.ts",
    purpose: "persistOperationalGovernanceBrief upserts operational_governance_briefs after the initial project-brief generation flow. Accepts an optional caller-supplied client (used by in-request callers with a scoped session); defaults to a fresh privileged client when none is supplied, for background/system callers that generate the brief asynchronously after the request has returned — same no-session-left-to-scope justification as evidence-processor.ts and discovery-repository.ts. loadLatestOperationalGovernanceBrief (read) always requires an explicit caller-supplied client and never creates a privileged client itself.",
    riskLevel: "MEDIUM",
    mitigations: [
      "workspaceId/projectId/createdBy are always sourced from the already-authorized brief-generation flow, never client input at this layer",
      "Callers with an active session pass their own scoped client via the `supabase` parameter, so the default privileged client only activates for the session-less background path",
    ],
    strictCriteriaMet: "L2",
    needsRlsBeforeSwap: false,
  },
  {
    file: "src/app/(protected)/dashboard/page.tsx",
    purpose: "Reads a single projects row (id, limit 1) scoped to the resolved workspaceId, to decide onboarding/idle-state copy. projects already has a workspace-member RLS policy (20260512160000_workspace_authorization_rewrite.sql) that permits this exact scoped read for an authenticated member — service role is used here for consistency with the page's other service-role reads on the same request. Documented as a SWAP candidate, not swapped in this pass.",
    riskLevel: "MEDIUM",
    mitigations: [
      "workspaceId always comes from resolveCanonicalWorkspace(user.id), never a query/body param",
      "Read-only, single row, no mutation",
    ],
    needsRlsBeforeSwap: false,
  },
  {
    file: "src/lib/security/abuse-protection.ts",
    purpose: "Perilla 9 — createSupabaseAbuseStore() calls abuse_rate_limit_increment() (a service-role-only RPC on abuse_rate_limits) to persist rate-limit counters. abuse_rate_limits is not tenant data and must never be readable/writable by an authenticated client at all — the table has no authenticated/anon RLS policy, so this must go through the service role regardless of caller identity.",
    riskLevel: "MEDIUM",
    mitigations: [
      "Only ever writes a hashed identifier + non-identifying metadata (redactAbuseMetadata strips token/email/secret-like keys before the call)",
      "The RPC itself is granted to service_role only (revoked from public/anon/authenticated in the migration)",
      "No caller-supplied value reaches this client directly — scope/action/identifierHash are all computed inside enforceAbuseLimit before this store is invoked",
    ],
    strictCriteriaMet: "L3",
    needsRlsBeforeSwap: false,
  },
  {
    file: "src/lib/ai/usage-accounting.ts",
    purpose:
      "Perilla 11 — records one ai_usage_events row per inference call and reads back the workspace's daily estimated cost for the AI_DAILY_COST_LIMIT_USD ceiling. ai_usage_events is operational accounting, not tenant-authored data, and is service-role-only by design (no authenticated/anon policy at all — 20260821000000_ai_usage_events.sql), so both the write and the ceiling read must use the privileged client regardless of caller identity.",
    riskLevel: "MEDIUM",
    mitigations: [
      "Writes only provider/model/operation identifiers, token counts, estimated cost, status, and ids — never prompt or response content",
      "Recording is best-effort and wrapped in try/catch: a failure logs a redacted warning and never propagates caller data or errors",
      "The daily-cost read filters by workspace_id + created_at only and returns a single aggregate number to the router's ceiling check",
    ],
    strictCriteriaMet: "L3",
    needsRlsBeforeSwap: false,
  },
] as const;

export function assertPrivilegedAccessJustified(file: string): void {
  const found = PRIVILEGED_ACCESS_REGISTRY.some((entry) => entry.file === file);
  if (!found) {
    throw new Error(
      `Privileged access is not registered for "${file}". ` +
        `Add an entry to src/lib/security/privileged-access-registry.ts before using service role here.`,
    );
  }
}
